@startuml

class Biblioteca{
    object[] biblioteca
    mostrar_biblioteca()
    
}

abstract class Elementos{
    nombre
    año
    disponible
    entregar_info()
}

class Libros{
    autor
    genero
    
}

class Revista{
    editorial
    periodicidad
}

class Periodico{
    fecha
    pais
}

class Multimedia{
    duracion
    formato
}



Elementos <|-- Libros
Elementos <|-- Revista
Elementos <|-- Periodico
Elementos <|-- Multimedia
Biblioteca *-- Elementos

@enduml